"""Remove flexible_goals and goal_templates tables

Revision ID: 07cdec3a9feb
Revises: 54c6826b8b0e
Create Date: 2025-08-12 01:02:01.944325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cdec3a9feb'
down_revision = '54c6826b8b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_templates')
    op.drop_table('craving_predictions')
    op.drop_table('flexible_goals')
    op.drop_table('user_patterns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_patterns',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('pattern_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pattern_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('pattern_data', sa.TEXT(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('sample_size', sa.INTEGER(), nullable=True),
    sa.Column('last_occurrence', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flexible_goals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('template_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('goal_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('target_value', sa.FLOAT(), nullable=False),
    sa.Column('current_value', sa.FLOAT(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('initial_target', sa.FLOAT(), nullable=True),
    sa.Column('reduction_rate', sa.FLOAT(), nullable=True),
    sa.Column('reduction_frequency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('current_streak', sa.INTEGER(), nullable=True),
    sa.Column('best_streak', sa.INTEGER(), nullable=True),
    sa.Column('success_count', sa.INTEGER(), nullable=True),
    sa.Column('attempt_count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['goal_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('craving_predictions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('prediction_date', sa.DATE(), nullable=False),
    sa.Column('prediction_hour', sa.INTEGER(), nullable=True),
    sa.Column('risk_score', sa.FLOAT(), nullable=False),
    sa.Column('confidence_level', sa.FLOAT(), nullable=True),
    sa.Column('risk_factors', sa.TEXT(), nullable=True),
    sa.Column('actual_craving_occurred', sa.BOOLEAN(), nullable=True),
    sa.Column('actual_craving_intensity', sa.INTEGER(), nullable=True),
    sa.Column('prediction_accuracy', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('template_config', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
