"""add_daily_reset_time_to_user_preferences

Revision ID: 2147fb57a0f9
Revises: b0c48f397cdf
Create Date: 2025-08-09 08:17:16.904969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2147fb57a0f9'
down_revision = 'b0c48f397cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_reset_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('daily_reset_time')
    # ### end Alembic commands ###
