"""Move preferred_brands and units_preference to UserPreferences

Revision ID: 6848755d9016
Revises: f8e091ac4f79
Create Date: 2025-08-24 01:14:01.898060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6848755d9016'
down_revision = 'f8e091ac4f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add new columns to user_preferences, making them nullable for now
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units_preference', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('preferred_brands', sa.JSON(), nullable=True))

    # Step 2: Data migration from user to user_preferences
    conn = op.get_bind()
    conn.execute(sa.text(
        "UPDATE user_preferences up JOIN user u ON up.user_id = u.id "
        "SET up.units_preference = u.units_preference, up.preferred_brands = u.preferred_brands"
    ))

    # Step 3: Set default for any rows that still have NULL for units_preference
    op.execute("UPDATE user_preferences SET units_preference = 'mg' WHERE units_preference IS NULL")

    # Step 4: Alter units_preference to be non-nullable as per the model
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('units_preference',
                              existing_type=sa.String(length=20),
                              nullable=False)

    # Step 5: Drop the old columns from the user table
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferred_brands')
        batch_op.drop_column('units_preference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add columns back to user table
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units_preference', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('preferred_brands', sa.Text(), nullable=True))

    # Step 2: Data migration from user_preferences back to user
    conn = op.get_bind()
    conn.execute(sa.text(
        "UPDATE user u JOIN user_preferences up ON u.id = up.user_id "
        "SET u.units_preference = up.units_preference, u.preferred_brands = up.preferred_brands"
    ))

    # Step 3: Drop columns from user_preferences
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('preferred_brands')
        batch_op.drop_column('units_preference')
    # ### end Alembic commands ###
