"""Add new database tables for improved schema

Revision ID: b0c48f397cdf
Revises: 5987ee8dd6f9
Create Date: 2025-08-09 00:18:19.019258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c48f397cdf'
down_revision = '5987ee8dd6f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('attempts_made', sa.Integer(), nullable=False),
    sa.Column('original_queue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_token'), ['token'], unique=True)

    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('goal_notifications', sa.Boolean(), nullable=False),
    sa.Column('daily_reminders', sa.Boolean(), nullable=False),
    sa.Column('weekly_reports', sa.Boolean(), nullable=False),
    sa.Column('achievement_notifications', sa.Boolean(), nullable=False),
    sa.Column('discord_webhook', sa.Text(), nullable=True),
    sa.Column('slack_webhook', sa.Text(), nullable=True),
    sa.Column('reminder_time', sa.Time(), nullable=True),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('notification_frequency', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('default_view', sa.String(length=20), nullable=False),
    sa.Column('chart_theme', sa.String(length=20), nullable=False),
    sa.Column('logs_per_page', sa.Integer(), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('time_format', sa.String(length=10), nullable=False),
    sa.Column('show_weekly_summary', sa.Boolean(), nullable=False),
    sa.Column('show_monthly_summary', sa.Boolean(), nullable=False),
    sa.Column('show_goal_progress', sa.Boolean(), nullable=False),
    sa.Column('show_recent_logs', sa.Boolean(), nullable=False),
    sa.Column('default_chart_period', sa.String(length=20), nullable=False),
    sa.Column('chart_animation', sa.Boolean(), nullable=False),
    sa.Column('show_trend_lines', sa.Boolean(), nullable=False),
    sa.Column('show_nicotine_content', sa.Boolean(), nullable=False),
    sa.Column('show_brand_info', sa.Boolean(), nullable=False),
    sa.Column('compact_view', sa.Boolean(), nullable=False),
    sa.Column('hide_sensitive_data', sa.Boolean(), nullable=False),
    sa.Column('anonymous_mode', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token')
        batch_op.drop_column('reset_token_expires')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_expires', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=100), nullable=True))

    op.drop_table('user_settings')
    op.drop_table('user_preferences')
    op.drop_table('user_activity')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_token'))

    op.drop_table('password_resets')
    op.drop_table('notification_queue')
    op.drop_table('notification_history')
    # ### end Alembic commands ###
