"""feat: Replace email_notifications with notification_channel

Revision ID: c77fe9364d1b
Revises: e58b108024a6
Create Date: 2025-08-10 09:28:03.949601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77fe9364d1b'
down_revision = 'e58b108024a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_channel', sa.String(length=20), nullable=True))

    # Data migration
    op.execute("""
        UPDATE user_preferences
        SET notification_channel = CASE
            WHEN email_notifications = 1 THEN 'email'
            ELSE 'none'
        END
    """)

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('notification_channel',
               existing_type=sa.String(length=20),
               nullable=False,
               server_default='email')
        batch_op.drop_column('email_notifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_notifications', sa.BOOLEAN(), nullable=True))

    # Data migration
    op.execute("""
        UPDATE user_preferences
        SET email_notifications = CASE
            WHEN notification_channel IN ('email', 'both') THEN 1
            ELSE 0
        END
    """)

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('email_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.true())
        batch_op.drop_column('notification_channel')

    # ### end Alembic commands ###
