"""Remove unnecessary verification columns from user table

Revision ID: e58b108024a6
Revises: 6bf4b3dbe561
Create Date: 2025-08-10 01:12:54.598169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58b108024a6'
down_revision = '6bf4b3dbe561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verification_attempts')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('last_verification_sent')
        batch_op.drop_column('verification_token_expires')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token_expires', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_verification_sent', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('verification_attempts', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
