"""feat: Store notification channels as a JSON list

Revision ID: f8e091ac4f79
Revises: 9a3d3841f6c1
Create Date: 2025-08-12 08:03:50.723219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8e091ac4f79'
down_revision = '9a3d3841f6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Data migration from string to JSON array string format
    op.execute("UPDATE user_preferences SET notification_channel = '[\"email\"]' WHERE notification_channel = 'email'")
    op.execute("UPDATE user_preferences SET notification_channel = '[\"discord\"]' WHERE notification_channel = 'discord'")
    op.execute("UPDATE user_preferences SET notification_channel = '[\"email\", \"discord\"]' WHERE notification_channel = 'both'")
    op.execute("UPDATE user_preferences SET notification_channel = '[]' WHERE notification_channel = 'none'")

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('notification_channel',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.JSON(),
               nullable=False,
               server_default=sa.text("'[\"email\"]'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This is a lossy conversion. We'll take the first element if it exists.
    op.execute("UPDATE user_preferences SET notification_channel = 'none' WHERE JSON_LENGTH(notification_channel) = 0")
    op.execute("UPDATE user_preferences SET notification_channel = JSON_UNQUOTE(JSON_EXTRACT(notification_channel, '$[0]')) WHERE JSON_LENGTH(notification_channel) > 0")

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('notification_channel',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=20),
               nullable=False,
               server_default=sa.text("'email'"))

    # ### end Alembic commands ###
