"""Dated target generated by a plan revision."""

from datetime import datetime

from extensions import db


class PlanDay(db.Model):
    __tablename__ = 'plan_day'
    __table_args__ = (
        db.UniqueConstraint(
            'plan_id', 'local_date', name='uq_plan_day_plan_local_date'
        ),
        db.ForeignKeyConstraint(
            ['plan_id', 'revision_id'],
            ['plan_revision.plan_id', 'plan_revision.id'],
            name='fk_plan_day_plan_revision',
            ondelete='CASCADE',
        ),
        db.CheckConstraint(
            '(target_pouches IS NULL AND nicotine_ceiling_mg IS NULL) OR '
            '(target_pouches IS NOT NULL AND target_pouches >= 0 AND '
            'nicotine_ceiling_mg IS NOT NULL AND nicotine_ceiling_mg >= 0)',
            name='ck_plan_day_target_pair',
        ),
    )

    id = db.Column(db.Integer, primary_key=True)
    plan_id = db.Column(db.Integer, nullable=False)
    revision_id = db.Column(db.Integer, nullable=False)
    local_date = db.Column(db.Date, nullable=False)
    target_pouches = db.Column(db.Integer, nullable=True)
    nicotine_ceiling_mg = db.Column(db.Numeric(8, 2), nullable=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    revision = db.relationship(
        'PlanRevision',
        backref=db.backref('days', cascade='all, delete-orphan'),
        foreign_keys=[plan_id, revision_id],
    )
